// Generated by https://quicktype.io

namespace Deserializer.Models
{
    using System;

    public class Temperature
    {     
        public DateOnly Date { get; set; }     
        public long TemperatureC { get; set; }     
        public string? Summary { get; set; }
        public long TemperatureF { get; set; }
    }
}
